### ISSUE TITLE
Issues with IMM13 document

### ISSUE THREAD

**Issue by jdixosnd** [BlinkID/blinkid-cordova#97] opened 2019-01-18 04:14 UTC
### Description :
There are different types of IMM13 documents('Single entry visa','visa pass') which starts from different series(please find attached images 'one' and 'two' ).
![two](https://user-images.githubusercontent.com/11541260/51365234-4c46b700-1b05-11e9-9971-5eae026d00f9.jpeg)
![one](https://user-images.githubusercontent.com/11541260/51365235-4c46b700-1b05-11e9-9bc6-ad9115df9c01.png)

For Image 'one' I am getting the response from scan with document type 4. But for image 'two' I am not getting response and eventually it fails.

I am using MRTDRecognizer like below,
```
recognizer = new (<any>window).cordova.plugins.BlinkID.MrtdRecognizer();
documentOverlaySettings = new <any>window).cordova.plugins.BlinkID.DocumentVerificationOverlaySettings();
```
Moreover, I want to know for which card the service will return 6 as all the cards are of IMM13.

### Environment Details
**BlinkID version:**
4.4.1
**Device model:**
OnePlus 5T
**Device Android version:**
Pie
**Device ABI (processor architecture, e.g. ARMv7):**
Qualcomm Snapdragon 835 MSM8998

**Comment by culoi** [comment] 2019-01-18 08:16
Hello @jdixosnd 

Can you please try to scan the Pass with our BlinkID app from the Play Store: https://play.google.com/store/apps/details?id=com.microblink.blinkidapp

We are performing some internal tests on the document and will let you know once we find out more info. 

In meantime, please test with the BlinkID app from the store just to make sure that the issue is not in the version of the SDK that you are using. 

Best regards

**Comment by jdixosnd** [comment] 2019-01-18 11:03
Hi @culoi !,

Your prompt response is highly appreciated.

As suggested by you I have also tried with the BlinkID app from the Play Store but sadly it also failed to scan, I have tried with PASSPORT and VISA category in the app.

**Comment by jdixosnd** [comment] 2019-01-21 10:59
Hi @culoi ,
Any update on this?

**Comment by Cerovec** [comment] 2020-03-27 11:31
Hi @jdixosnd,

Sorry for the long delay, we hope you managed to resolve this successfully. In any case, for IMM13 documents we've added the feature to `allowSpecialCharacters` in our MrtdRecognizer, which allows you to scan all types of IMM13 documents. 

Let us know if this is still an issue for you.

Thanks!
Jurica.

**Comment by Cerovec** [comment] 2020-04-10 16:02
Hi @jdixosnd,

We hope you managed to solve this issue. We'll close this issue for the moment. If you need anything else please be free to open another issue or reopen this one.

Thanks,
Jurica.

**Closed by Cerovec** 2020-04-10 16:02 UTC
Labels: help wanted
